spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/censusdb
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
    platform: POSTGRESQL